# Generated by Django 4.0.6 on 2022-07-27 11:59

import agregator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0004_baseword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseword',
            name='file',
            field=models.FileField(default=None, upload_to=agregator.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='file_state',
            field=models.FileField(default=None, upload_to=agregator.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='type',
            field=models.TextField(default=None),
        ),
    ]
