# Generated by Django 4.0.6 on 2022-07-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agregator', '0005_alter_baseword_file_alter_baseword_file_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseword',
            name='uid',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='baseparsingresult',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agregator.baseword'),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
