# Generated by Django 4.0.6 on 2022-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0006_baseword_uid_alter_baseparsingresult_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseword',
            name='task_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
