# Generated by Django 4.0.6 on 2022-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0007_baseword_task_id_alter_baseword_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseword',
            name='uid',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
