# Generated by Django 4.0.6 on 2022-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0008_alter_baseword_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseparsingresult',
            name='data',
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='date_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='date_ot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='number_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='result_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='baseparsingresult',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseparsingresult',
            name='task_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
