# Generated by Django 4.0.6 on 2022-07-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0009_remove_baseparsingresult_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseword',
            old_name='task_id',
            new_name='name',
        ),
    ]
