# Generated by Django 4.0.6 on 2022-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0010_rename_task_id_baseword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseword',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
