# Generated by Django 4.0.6 on 2022-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0011_alter_baseword_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseparsingresult',
            name='uid',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
