# Generated by Django 4.0.6 on 2022-07-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0012_baseparsingresult_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparsingresult',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='agregator.baseword'),
        ),
    ]
