# Generated by Django 4.0.6 on 2022-08-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0015_baseparsingresult_file_word_baseword_file_acrhiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparsingresult',
            name='file_word',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
