# Generated by Django 4.0.6 on 2022-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0018_alter_baseparsingresult_file_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparsingresult',
            name='file_word',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
