# Generated by Django 4.0.6 on 2022-08-05 12:58

import agregator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0019_alter_baseparsingresult_file_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseword',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=agregator.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='file_acrhiv',
            field=models.FileField(default=None, null=True, upload_to=agregator.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='file_state',
            field=models.FileField(default=None, null=True, upload_to=agregator.models.user_directory_path),
        ),
    ]
