# Generated by Django 3.2.9 on 2022-08-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0021_auto_20220812_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparsingresult',
            name='uid',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='baseword',
            name='uid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
