# Generated by Django 4.0.6 on 2022-07-22 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
            ],
        ),
    ]
